version: "3"

services:
  app:
    image: s10akir/moja-radio:latest
    volumes:
      - ./rules.json:/usr/src/app/rules.json
      - ./oauth_credentials:/usr/src/app/oauth_credentials
    environment:
      - TZ=Asia/Tokyo
